
import { KPIMetric, ActiveCall, Booking, Customer, Lead, Event, Call, Agent, WhatsAppTemplate, Theme, Alert } from './types';

export const kpiMetrics: KPIMetric[] = [
  {
    id: 'fcr',
    label: 'First Call Resolution',
    value: '78%',
    target: '75-85%',
    trend: 'up',
    status: 'good',
    sparklineData: [72, 74, 76, 75, 77, 78, 79, 78]
  },
  {
    id: 'acd',
    label: 'Avg Call Duration',
    value: '6.2 min',
    target: '4-8 min',
    trend: 'down',
    status: 'good',
    sparklineData: [6.8, 6.5, 6.4, 6.3, 6.2, 6.1, 6.2, 6.2]
  },
  {
    id: 'abandonment',
    label: 'Abandonment Rate',
    value: '6.8%',
    target: '<8%',
    trend: 'stable',
    status: 'warning',
    sparklineData: [7.2, 6.9, 6.8, 7.0, 6.8, 6.7, 6.8, 6.8]
  },
  {
    id: 'csat',
    label: 'Customer Satisfaction',
    value: '87%',
    target: '>85%',
    trend: 'up',
    status: 'good',
    sparklineData: [83, 84, 85, 86, 86, 87, 88, 87]
  },
  {
    id: 'ces',
    label: 'Customer Effort Score',
    value: '2.3',
    target: '<3.0',
    trend: 'down',
    status: 'good',
    sparklineData: [2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.3]
  },
  {
    id: 'sentiment',
    label: 'Live Positive Sentiment',
    value: '68%',
    target: '≥65%',
    trend: 'up',
    status: 'good',
    sparklineData: [64, 65, 66, 67, 68, 69, 68, 68]
  },
  {
    id: 'cost',
    label: 'Cost per Contact',
    value: '$4.20',
    target: '<$5.60',
    trend: 'down',
    status: 'good',
    sparklineData: [4.8, 4.7, 4.6, 4.5, 4.3, 4.2, 4.1, 4.2]
  },
  {
    id: 'utilization',
    label: 'Agent Utilization',
    value: '82.4%',
    target: '75-85%',
    trend: 'stable',
    status: 'good',
    sparklineData: [80, 81, 82, 83, 82, 82, 83, 82]
  }
];

export const activeCalls: ActiveCall[] = [
    {
      id: 'call-1',
      customerId: 'cust-123',
      customerName: 'Jennifer Williams',
      agentId: 'agent-7',
      agentName: 'AI Agent 7',
      duration: 320,
      sentiment: 'positive',
      sentimentScore: 85,
      topic: 'Booking Inquiry',
      status: 'active',
      startTime: new Date('2024-07-31T14:25:00Z'),
    },
    {
      id: 'call-2',
      customerId: 'cust-456',
      customerName: 'Michael Brown',
      agentId: 'agent-2',
      agentName: 'AI Agent 2',
      duration: 150,
      sentiment: 'neutral',
      sentimentScore: 55,
      topic: 'Pricing Question',
      status: 'on-hold',
      startTime: new Date('2024-07-31T14:28:00Z'),
    },
    {
      id: 'call-3',
      customerId: 'cust-789',
      customerName: 'Jessica Davis',
      agentId: 'agent-18',
      agentName: 'Sarah Clark',
      duration: 550,
      sentiment: 'negative',
      sentimentScore: 25,
      topic: 'Complaint',
      status: 'active',
      startTime: new Date('2024-07-31T14:20:00Z'),
    },
    {
        id: 'call-4',
        customerId: 'cust-101',
        customerName: 'David Martinez',
        agentId: 'agent-5',
        agentName: 'AI Agent 5',
        duration: 210,
        sentiment: 'positive',
        sentimentScore: 92,
        topic: 'Modification Request',
        status: 'transferring',
        startTime: new Date('2024-07-31T14:26:00Z'),
    },
];

export const recentBookings: Booking[] = [
  {
    id: 'booking-1',
    customerId: 'cust-1',
    customerName: 'Linda Robinson',
    eventType: 'Wedding',
    eventDate: new Date('2024-12-15T14:00:00Z'),
    guestCount: 150,
    value: 12500,
    status: 'confirmed',
    paymentMethod: 'credit',
    paymentStatus: 'paid',
    createdAt: new Date('2024-07-20T10:30:00Z'),
  },
  {
    id: 'booking-2',
    customerId: 'cust-2',
    customerName: 'Tech Corp',
    eventType: 'Conference',
    eventDate: new Date('2024-11-20T09:00:00Z'),
    guestCount: 300,
    value: 25000,
    status: 'pending',
    paymentMethod: 'bank',
    paymentStatus: 'pending',
    createdAt: new Date('2024-07-18T15:00:00Z'),
  },
  {
    id: 'booking-3',
    customerId: 'cust-3',
    customerName: 'Global Enterprises',
    eventType: 'Product Launch',
    eventDate: new Date('2024-10-05T18:00:00Z'),
    guestCount: 200,
    value: 8500,
    status: 'confirmed',
    paymentMethod: 'credit',
    paymentStatus: 'paid',
    createdAt: new Date('2024-07-15T11:45:00Z'),
  },
  {
    id: 'booking-4',
    customerId: 'cust-4',
    customerName: 'Emily Martin',
    eventType: 'Birthday Party',
    eventDate: new Date('2024-09-30T19:00:00Z'),
    guestCount: 50,
    value: 3500,
    status: 'confirmed',
    paymentMethod: 'wallet',
    paymentStatus: 'paid',
    createdAt: new Date('2024-07-12T09:20:00Z'),
  },
  {
    id: 'booking-5',
    customerId: 'cust-5',
    customerName: 'Future Solutions',
    eventType: 'Gala Dinner',
    eventDate: new Date('2025-01-20T20:00:00Z'),
    guestCount: 250,
    value: 18000,
    status: 'cancelled',
    paymentMethod: 'credit',
    paymentStatus: 'refunded',
    createdAt: new Date('2024-07-10T16:00:00Z'),
  },
];

export const customers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Linda Robinson',
    email: 'linda.robinson@example.com',
    phone: '+1-555-0101',
    type: 'individual',
    status: 'active',
    totalBookings: 3,
    totalValue: 28000,
    lifetime: 365,
    lastContact: new Date('2024-07-20T10:30:00Z'),
    sentiment: 'positive',
    tags: ['VIP', 'Frequent'],
    createdAt: new Date('2023-07-31T10:00:00Z'),
  },
  {
    id: 'cust-2',
    name: 'Tech Corp',
    email: 'contact@techcorp.com',
    phone: '+1-555-0102',
    type: 'corporate',
    status: 'active',
    totalBookings: 5,
    totalValue: 120000,
    lifetime: 730,
    lastContact: new Date('2024-07-18T15:00:00Z'),
    sentiment: 'neutral',
    tags: ['Corporate', 'High-Value'],
    createdAt: new Date('2022-07-31T11:00:00Z'),
  },
  {
    id: 'cust-3',
    name: 'Global Enterprises',
    email: 'events@globalenterprises.com',
    phone: '+1-555-0103',
    type: 'corporate',
    status: 'inactive',
    totalBookings: 1,
    totalValue: 8500,
    lifetime: 180,
    lastContact: new Date('2024-01-15T11:45:00Z'),
    sentiment: 'neutral',
    tags: ['At-Risk'],
    createdAt: new Date('2024-02-02T12:00:00Z'),
  },
];

export const leads: Lead[] = [
    {
      id: 'lead-1',
      name: 'John Smith',
      email: 'john.smith@example.com',
      phone: '+1-555-0104',
      source: 'Website',
      status: 'new',
      score: 85,
      eventType: 'Wedding',
      expectedValue: 15000,
      notes: 'Initial inquiry, high interest.',
      createdAt: new Date('2024-07-30T10:00:00Z'),
    },
    {
      id: 'lead-2',
      name: 'Mary Garcia',
      email: 'mary.garcia@example.com',
      phone: '+1-555-0105',
      source: 'Referral',
      status: 'qualified',
      score: 95,
      eventType: 'Corporate Event',
      expectedValue: 30000,
      followUpDate: new Date('2024-08-05T10:00:00Z'),
      notes: 'Referred by Tech Corp. Proposal sent.',
      createdAt: new Date('2024-07-28T14:30:00Z'),
    }
];

export const events: Event[] = [
    {
      id: 'event-1',
      name: 'Tech Corp Annual Conference',
      type: 'Conference',
      venue: 'Grand Ballroom',
      date: new Date('2024-11-20T09:00:00Z'),
      status: 'confirmed',
      capacity: 300,
      booked: 280,
      revenue: 25000,
      customerId: 'cust-2',
      customerName: 'Tech Corp',
    },
    {
      id: 'event-2',
      name: 'Linda & John\'s Wedding',
      type: 'Wedding',
      venue: 'Riverside Garden',
      date: new Date('2024-12-15T14:00:00Z'),
      status: 'confirmed',
      capacity: 150,
      booked: 150,
      revenue: 12500,
      customerId: 'cust-1',
      customerName: 'Linda Robinson',
    },
];

export const calls: Call[] = [
    {
        id: 'call-101',
        customerId: 'cust-123',
        customerName: 'Jennifer Williams',
        agentId: 'agent-7',
        agentName: 'AI Agent 7',
        agentType: 'ai',
        direction: 'inbound',
        duration: 320,
        outcome: 'resolved',
        sentiment: 'positive',
        sentimentJourney: [20, 40, 60, 80, 75, 85, 90, 80, 70, 95],
        topics: ['Booking Inquiry', 'Pricing'],
        intentRecognized: true,
        intentAccuracy: 95,
        transcript: 'Customer inquired about booking a wedding in December. AI provided package details and pricing. Customer was satisfied.',
        startTime: new Date('2024-07-31T14:25:00Z'),
        endTime: new Date('2024-07-31T14:30:20Z'),
        cost: 1.50,
        qualityScore: 98,
    },
    {
        id: 'call-102',
        customerId: 'cust-789',
        customerName: 'Jessica Davis',
        agentId: 'agent-18',
        agentName: 'Sarah Clark',
        agentType: 'human',
        direction: 'inbound',
        duration: 550,
        outcome: 'transferred',
        sentiment: 'negative',
        sentimentJourney: [60, 50, 40, 30, 20, 15, 10, 25, 30, 20],
        topics: ['Complaint', 'Payment Issue'],
        intentRecognized: false,
        intentAccuracy: 0,
        transcript: 'Customer was unhappy about a payment issue. Call was escalated to a senior agent for resolution.',
        startTime: new Date('2024-07-31T14:20:00Z'),
        endTime: new Date('2024-07-31T14:29:10Z'),
        cost: 7.20,
        qualityScore: 75,
    }
];

export const agents: Agent[] = [
  {
    id: 'agent-1',
    name: 'AI Agent 1',
    type: 'ai' as const,
    status: 'available',
    skills: ['Booking', 'Sales'],
    performanceMetrics: { fcr: 85, acd: 5.5, csat: 92, qualityScore: 95, utilization: 80, callsToday: 45 },
  },
  {
    id: 'agent-2',
    name: 'AI Agent 2',
    type: 'ai' as const,
    status: 'busy',
    skills: ['Support', 'Technical'],
    performanceMetrics: { fcr: 78, acd: 7.2, csat: 88, qualityScore: 91, utilization: 85, callsToday: 52 },
    currentCall: 'call-2',
  },
  {
    id: 'agent-16',
    name: 'Sarah Clark',
    type: 'human' as const,
    status: 'busy',
    skills: ['Support', 'Complaints'],
    performanceMetrics: { fcr: 75, acd: 8.1, csat: 85, qualityScore: 88, utilization: 70, callsToday: 35 },
    currentCall: 'call-3',
  },
  {
    id: 'agent-17',
    name: 'John Doe',
    type: 'human' as const,
    status: 'available',
    skills: ['Sales', 'Booking'],
    performanceMetrics: { fcr: 82, acd: 6.5, csat: 90, qualityScore: 92, utilization: 75, callsToday: 41 },
  },
];

export const whatsappTemplates: WhatsAppTemplate[] = [
    {
        id: 'template-1',
        name: 'Booking Confirmation',
        category: 'Transactional',
        content: 'Hello {{name}}, your booking for {{event}} on {{date}} is confirmed!',
        status: 'active',
        language: 'en',
        metrics: { sent: 5230, delivered: 5180, read: 4950, clicked: 850, converted: 210 },
        createdAt: new Date('2024-06-01T10:00:00Z'),
    },
    {
        id: 'template-2',
        name: 'Special Offer',
        category: 'Marketing',
        content: 'Hi {{name}}, get 20% off your next event booking with us! Use code: EVENT20',
        status: 'active',
        language: 'en',
        metrics: { sent: 10500, delivered: 10300, read: 8500, clicked: 1500, converted: 350 },
        createdAt: new Date('2024-07-01T11:00:00Z'),
    },
];

export const themes: Theme[] = [
    {
        id: 'theme-1',
        name: 'Classic Wedding',
        description: 'Timeless elegance for your special day.',
        basePrice: 5000,
        category: 'Wedding',
        features: ['Venue', 'Catering', 'Decoration'],
        status: 'active',
        popularity: 85,
        bookings: 120,
        revenue: 600000,
    },
    {
        id: 'theme-2',
        name: 'Modern Corporate',
        description: 'Sleek and professional for business events.',
        basePrice: 7500,
        category: 'Corporate',
        features: ['Venue', 'AV Equipment', 'Catering'],
        status: 'active',
        popularity: 92,
        bookings: 85,
        revenue: 637500,
    },
];

export const alerts: Alert[] = [
  {
    id: 'alert-1',
    type: 'critical',
    title: 'Queue Wait Time Exceeded',
    message: 'Average wait time is now 8 minutes, exceeding the 5-minute threshold',
    timestamp: new Date(Date.now() - 300000),
    read: false
  },
  {
    id: 'alert-2',
    type: 'warning',
    title: 'High Call Volume',
    message: '15% increase in call volume compared to last hour',
    timestamp: new Date(Date.now() - 600000),
    read: false
  },
  {
    id: 'alert-3',
    type: 'info',
    title: 'Agent Shift Change',
    message: '3 agents going on break in 10 minutes',
    timestamp: new Date(Date.now() - 900000),
    read: true
  }
];
